// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjnhunrbzunwkfjivynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbmh1bnJienVud2tmaml2eW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjc2ODEsImV4cCI6MjA2Nzk0MzY4MX0.Y_HzCbIXcWgTkhe7w0ts5hQUmEM_9eaT4UXoltunx8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});